---
- name: Synapse checks
  block:

    - name: Check that matrix-synapse is available when debian is specified as the install source
      block:

        - name: Use apt show matrix-synapse to check if synapse is availabe 
          ansible.builtin.command: apt show matrix-synapse -a
          check_mode: false
          changed_when: false
          register: synapse_debian_apt_show_synapse
          failed_when: synapse_debian_apt_show_synapse.rc is not regex('^0|100$')

        - name: Fail if matrix-synapse is unavailabel on Debian Bullseye
          ansible.builtin.fail:
            msg: "Please ensure that Debian backports are enabled."
          when: synapse_debian_apt_show_synapse.rc == 100
      
      when: synapse_source == "debian"

  tags:
    - synapse
...
