---
- name: Synapse checks
  block:

    - name: Check Debian version
      ansible.builtin.assert:
        that:
          - ansible_distribution == "Debian"
          - ansible_distribution_release is ansible.builtin.regex('^bullseye|bookworm$')
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

    - name: Check that matrix-synapse is available when debian is specified as the install source
      block:

        - name: Use apt-cache policy matrix-synapse to check if synapse is availabe
          ansible.builtin.command: apt-cache policy matrix-synapse
          check_mode: false
          changed_when: false
          register: synapse_debian_apt_cache_policy_synapse

        - name: Fail if matrix-synapse is unavailable on Debian Bullseye
          ansible.builtin.assert:
            that:
              - ( "buster-backports" in synapse_debian_apt_cache_policy_synapse,stdout )
            quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
          when: ansible_distribution_release == "bullseye"

      when: synapse_source == "debian"

  tags:
    - synapse
    - synapse_checks
...
