---
- name: Configure synapse
  block:

    - name: Copy the homeserver.yaml file when it hasn't been modified using Ansible
      ansible.builtin.copy:
        src: /etc/matrix-synapse/homeserver.yaml
        dest: "{{ synapse_homeserver_backup }}"
        mode: 0600
        remote_src: true
      when:
        - not synapse_homeserver_backup_check.stat.exists | bool
        - synapse_homeserver_existing_config_lines[0] != "# Ansible managed"

    - name: Symlink the cert and key if present and valid
      block:

        - name: Cert symlinked
          ansible.builtin.file:
            state: link
            src: "{{ synapse_tls_certificate_path }}"
            dest: /etc/matrix-synapse/homeserver.tls.crt
            follow: false
            mode: 0777
            owner: matrix-synapse
            group: ssl-cert
          notify: Restart matrix-synapse

        - name: Key symlinked
          ansible.builtin.file:
            state: link
            src: "{{ synapse_tls_private_key_path }}"
            dest: /etc/matrix-synapse/homeserver.tls.key
            follow: false
            mode: 0777
            owner: matrix-synapse
            group: ssl-cert
          notify: Restart matrix-synapse

      when:
        - synapse_cert.stat.exists | bool
        - synapse_key.stat.exists | bool
        - synapse_cert_info.valid_at.tomorrow | bool
        - synapse_cert_info.subject.commonName == synapse_domain

    - name: Include PostgreSQL role to get the password
      ansible.builtin.include_role:
        name: postgresql
        tasks_from: pgpass_read.yml
      vars:
        postgresql_db: "{{ synapse_db.database.args.database }}"
        postgresql_user: "{{ synapse_db.database.args.user }}"

    - name: Set a fact for the PostgreSQL password
      ansible.builtin.set_fact:
        synapse_db_pass: "{{ postgresql_password }}"
      no_log: true

    - name: Synapse database.yaml config present
      ansible.builtin.template:
        src: database.yaml.j2
        dest: /etc/matrix-synapse/conf.d/database.yaml
        backup: true
        mode: 0640
        owner: matrix-synapse
        group: matrix-synapse
      when: >-
        ( synapse_database_existing_config is not defined ) or
        ( synapse_database_existing_config | length == 0 ) or
        ( synapse_database_existing_config != synapse_db )
      notify: Restart matrix-synapse

    - name: Synapse secrets present
      ansible.builtin.include_tasks: secrets.yml
      loop: "{{ synapse_secrets }}"
      loop_control:
        loop_var: synapse_secret

    - name: Synapse homeserver.yaml config present
      ansible.builtin.template:
        src: homeserver.yaml.j2
        dest: /etc/matrix-synapse/homeserver.yaml
        backup: true
        mode: 0640
        owner: matrix-synapse
        group: matrix-synapse
      when: synapse_homeserver_existing_config != synapse_homeserver
      notify: Restart matrix-synapse

    - name: Nginx config
      block:

        - name: Synapse Nginx config present in sites-available
          ansible.builtin.template:
            src: nginx.conf.j2
            dest: "/etc/nginx/sites-available/{{ synapse_domain }}.conf"
            backup: true
            mode: 0644
            owner: root
            group: root

        - name: Stat synapse Nginx config in sites-available
          ansible.builtin.stat:
            path: "/etc/nginx/sites-available/{{ synapse_domain }}.conf"
          register: synapse_nginx_site_available

        - name: Synapse Nginx config config symlinked from sutes-enabled
          ansible.builtin.file:
            state: link
            src: "/etc/nginx/sites-available/{{ synapse_domain }}.conf"
            dest: "/etc/nginx/sites-enabled/{{ synapse_domain }}.conf"
            follow: false
            mode: 0777
            owner: root
            group: root
          when: synapse_nginx_site_available.stat.exists | bool

        - name: Nginx configtest # noqa yaml[comments] command-instead-of-module
          ansible.builtin.command: service nginx configtest
          check_mode: false
          changed_when: false

      notify: Restart nginx

    - name: PEM dh parameters for ephemeral keys present
      community.crypto.openssl_dhparam:
        path: /etc/matrix-synapse/homeserver.tls.dh
        size: 4096
        mode: 0640
        owner: matrix-synapse
        group: matrix-synapse
      notify: Restart matrix-synapse

  tags:
    - synapse
    - synapse_config
...
