---
- name: Configure synapse
  block:

    - name: Copy the homeserver.yaml file when it hasn't been modified using Ansible
      ansible.builtin.copy:
        src: /etc/matrix-synapse/homeserver.yaml
        dest: "{{ synapse_homeserver_backup }}"
        mode: 0600
        remote_src: true
      when:
        - not synapse_homeserver_backup_check.stat.exists | bool
        - synapse_homeserver_existing_config_lines[0] != "# Ansible managed"

    - name: Include PostgreSQL role to get the password
      ansible.builtin.include_role:
        name: postgresql
        tasks_from: pgpass_read.yml
      vars:
        postgresql_db: "{{ synapse_db_name }}"
        postgresql_user: "{{ synapse_db_user }}"

    - name: Set a fact for the PostgreSQL password
      ansible.builtin.set_fact:
        synapse_db_pass: "{{ postgresql_password }}"
      no_log: true

    - name: Synapse homeserver.yaml config present
      ansible.builtin.template:
        src: homeserver.yaml.j2
        dest: /etc/matrix-synapse/homeserver.yaml
        backup: true
        mode: 0640
        owner: matrix-synapse
        group: matrix-synapse
      when: synapse_homeserver_existing_config != synapse_homeserver
      notify: Restart matrix-synapse

    - name: Nginx config
      block:

        - name: Synapse Nginx config present in sites-available
          ansible.builtin.template:
            src: nginx.conf.j2
            dest: "/etc/nginx/sites-available/{{ synapse_domain }}.conf"
            backup: true
            mode: 0644
            owner: root
            group: root

        - name: Stat synapse Nginx config in sites-available
          ansible.builtin.stat:
            path: "/etc/nginx/sites-available/{{ synapse_domain }}.conf"
          register: synapse_nginx_site_available

        - name: Synapse Nginx config config symlinked from sutes-enabled
          ansible.builtin.file:
            state: link
            src: "/etc/nginx/sites-available/{{ synapse_domain }}.conf"
            dest: "/etc/nginx/sites-enabled/{{ synapse_domain }}.conf"
            follow: false
            mode: 0777
            owner: root
            group: root
          when: synapse_nginx_site_available.stat.exists | bool

        - name: Nginx configtest
          ansible.builtin.command: service nginx configtest
          check_mode: false
          changed_when: false

      notify: Restart nginx

    - name: PEM dh parameters for ephemeral keys present
      community.crypto.openssl_dhparam:
        path: /etc/matrix-synapse/homeserver.tls.dh
        size: 4096
        mode: 0600
        owner: matrix-synapse
        group: matrix-synapse
      notify: Restart matrix-synapse

  tags:
    - synapse
    - synapse_config
...
