# Copyright 2019-2023 Chris Croome
#
# This file is part of the Webarchitects Synapse Ansible role.
#
# The Webarchitects Synapse Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Synapse Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Synapse Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Synapse Debian install
  block:

    - name: Read the debconf for matrix-synapse
      ansible.builtin.shell: |
        set -e -o pipefail
        debconf-show matrix-synapse | sed 's/^[*]/ /' | sed 's/synapse\///'
      args:
        executable: /usr/bin/bash
      changed_when: false
      check_mode: false
      register: synapse_debconf_show

    - name: Set a fact for the debconf for matrix-synapse
      ansible.builtin.set_fact:
        synapse_debconf: "{{ synapse_debconf_show.stdout | string | community.general.jc('kv') }}"

    - name: Debug the debconf settings for matrix-synapse
      ansible.builtin.debug:
        var: synapse_debconf
        verbosity: 2

    - name: Debconf server-name
      ansible.builtin.debconf:
        name: matrix-synapse
        question: matrix-synapse/server-name
        value: "{{ synapse_server_name }}"
        vtype: text
      when: >-
        ( synapse_debconf['server-name'] is not defined ) or
        ( synapse_debconf['server-name'] != synapse_server_name )

    - name: Debconf report-stats
      ansible.builtin.debconf:
        name: matrix-synapse
        question: matrix-synapse/report-stats
        value: "{{ synapse_homeserver.report_stats | default(false) }}"
        vtype: text
      when: >-
        ( synapse_debconf['report-stats'] is not defined ) or
        ( synapse_debconf['report-stats'] != synapse_homeserver.report_stats )

    - name: Requirements present
      ansible.builtin.apt:
        pkg:
          - python3-authlib

    - name: Synapse present from backports on Debian Bullseye
      block:

        - name: Run apt-cache policy matrix-synapse
          ansible.builtin.command: apt-cache policy matrix-synapse
          check_mode: false
          changed_when: false
          register: synapse_apt_cache_policy_synapse

        - name: Install Synapse and dependencies from backports  # noqa yaml[comments] package-latest
          ansible.builtin.apt:
            pkg:
              - libpq5
              - matrix-synapse
            state: latest
            default_release: "{{ ansible_distribution_release }}-backports"
          when: ( "-backports" in synapse_apt_cache_policy_synapse.stdout )
          notify: Restart matrix-synapse

      when: ansible_distribution_release == "bullseye"

    - name: Synapse and dependencies present
      ansible.builtin.apt:
        pkg:
          - libpq5
          - matrix-synapse
        state: present
      when: ansible_distribution_release != "bullseye"
      notify: Restart matrix-synapse

    - name: Group for matrix-synapse present
      ansible.builtin.group:
        name: matrix-synapse
        state: present

    - name: User matrix-synapse is a member of the matrix-synapse and ssl-cert group
      ansible.builtin.user:
        name: matrix-synapse
        group: matrix-synapse
        groups:
          - ssl-cert
        append: true

    - name: Configuration directory ownership updated
      ansible.builtin.file:
        path: /etc/matrix-synapse
        state: directory
        mode: "0750"
        owner: root
        group: matrix-synapse

  tags:
    - synapse
    - synapse_install
...
