# Copyright 2019-2023 Chris Croome
#
# This file is part of the Webarchitects Synapse Ansible role.
#
# The Webarchitects Synapse Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Synapse Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Synapse Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Install, configure and upgrade synapse
  block:

    - name: Include synapse checks
      ansible.builtin.include_tasks: checks.yml
      tags:
        - synapse_acmesh
        - synapse_apt
        - synapse_checks
        - synapse_config
        - synapse_postgresql

    - name: Include synapse install tasks when installing from Debian apt repos
      ansible.builtin.include_tasks: debian.yml
      when: synapse_source == "debian"
      tags:
        - synapse_apt

    # TODO
    # - name: Include synapse install tasks when installing from synapse apt repos
    #   ansible.builtin.include_tasks: synapse.yml
    #   when: synapse_source == "synapse"
    #   tags:
    #     - synapse_apt

    - name: Include synapse configuration tasks
      ansible.builtin.include_tasks: config.yml
      when: synapse_etc_homeserver_yaml.stat.exists | bool
      tags:
        - synapse_acmesh
        - synapse_config
        - synapse_postgresql

  when: synapse | bool
  tags:
    - synapse
...
