---
- name: Install, configure and upgrade synapse
  block:

    - name: Include synapse checks
      ansible.builtin.include_tasks: checks.yml
      tags:
        - synapse_acmesh
        - synapse_apt
        - synapse_checks
        - synapse_config
        - synapse_postgresql

    - name: Include synapse install tasks when installing from Debian apt repos
      ansible.builtin.include_tasks: debian.yml
      when: synapse_source == "debian"
      tags:
        - synapse_apt

    # TODO
    # - name: Include synapse install tasks when installing from synapse apt repos
    #   ansible.builtin.include_tasks: synapse.yml
    #   when: synapse_source == "synapse"
    #   tags:
    #     - synapse_apt

    - name: Include synapse configuration tasks
      ansible.builtin.include_tasks: config.yml
      when: synapse_etc_homeserver_yaml.stat.exists | bool
      tags:
        - synapse_acmesh
        - synapse_config
        - synapse_postgresql

  when: synapse | bool
  tags:
    - synapse
...
