---
- name: Synapse secrets present
  block:

    - name: Stat the secret file
      ansible.builtin.stat:
        path: /etc/matrix-synapse/conf.d/{{ synapse_secret }}.yaml
      register: synapse_secret_file

    - name: Generate the secret if the secret file doesn't exist
      ansible.builtin.shell: |
        set -e -o pipefail
        echo "{{ synapse_secret }}: \"$(pwgen -s 51 1)\"" > {{ synapse_secret }}.yaml
        chown root:matrix-synapse {{ synapse_secret }}.yaml
        chmod 640 {{ synapse_secret }}.yaml
      args:
        chdir: /etc/matrix-synapse/conf.d
        creates: "/etc/matrix-synapse/conf.d/{{ synapse_secret }}.yaml"
        executable: /usr/bin/bash
      when: not synapse_secret_file.stat.exists | bool

  tags:
    - synapse
...
